# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 5-building-package.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import 5_street_package_pb2 as 5__street__package__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x35-building-package.proto\x12\texercise2\x1a\x16\x35-street-package.proto\"^\n\x08\x42uilding\x12\x15\n\rbuilding_name\x18\x01 \x01(\t\x12\x17\n\x0f\x62uilding_number\x18\x02 \x01(\x05\x12\"\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x11.exercise2.Streetb\x06proto3')



_BUILDING = DESCRIPTOR.message_types_by_name['Building']
Building = _reflection.GeneratedProtocolMessageType('Building', (_message.Message,), {
  'DESCRIPTOR' : _BUILDING,
  '__module__' : '5_building_package_pb2'
  # @@protoc_insertion_point(class_scope:exercise2.Building)
  })
_sym_db.RegisterMessage(Building)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUILDING._serialized_start=63
  _BUILDING._serialized_end=157
# @@protoc_insertion_point(module_scope)
