# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 5-street-package.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import 5_city_package_pb2 as 5__city__package__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x35-street-package.proto\x12\texercise2\x1a\x14\x35-city-package.proto\";\n\x06Street\x12\x12\n\naddr_line1\x18\x01 \x01(\t\x12\x1d\n\x04name\x18\x02 \x01(\x0b\x32\x0f.exercise2.Cityb\x06proto3')



_STREET = DESCRIPTOR.message_types_by_name['Street']
Street = _reflection.GeneratedProtocolMessageType('Street', (_message.Message,), {
  'DESCRIPTOR' : _STREET,
  '__module__' : '5_street_package_pb2'
  # @@protoc_insertion_point(class_scope:exercise2.Street)
  })
_sym_db.RegisterMessage(Street)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STREET._serialized_start=59
  _STREET._serialized_end=118
# @@protoc_insertion_point(module_scope)
