// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 5-building-package.proto

package exercise2;

public final class 5BuildingPackage {
  private 5BuildingPackage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BuildingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:exercise2.Building)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string building_name = 1;</code>
     * @return The buildingName.
     */
    java.lang.String getBuildingName();
    /**
     * <code>string building_name = 1;</code>
     * @return The bytes for buildingName.
     */
    com.google.protobuf.ByteString
        getBuildingNameBytes();

    /**
     * <code>int32 building_number = 2;</code>
     * @return The buildingNumber.
     */
    int getBuildingNumber();

    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.Street address = 3;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.Street address = 3;</code>
     * @return The address.
     */
    exercise2.5StreetPackage.Street getAddress();
    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.Street address = 3;</code>
     */
    exercise2.5StreetPackage.StreetOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code exercise2.Building}
   */
  public static final class Building extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:exercise2.Building)
      BuildingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Building.newBuilder() to construct.
    private Building(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Building() {
      buildingName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Building();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Building(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              buildingName_ = s;
              break;
            }
            case 16: {

              buildingNumber_ = input.readInt32();
              break;
            }
            case 26: {
              exercise2.5StreetPackage.Street.Builder subBuilder = null;
              if (address_ != null) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(exercise2.5StreetPackage.Street.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return exercise2.5BuildingPackage.internal_static_exercise2_Building_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return exercise2.5BuildingPackage.internal_static_exercise2_Building_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              exercise2.5BuildingPackage.Building.class, exercise2.5BuildingPackage.Building.Builder.class);
    }

    public static final int BUILDING_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object buildingName_;
    /**
     * <code>string building_name = 1;</code>
     * @return The buildingName.
     */
    @java.lang.Override
    public java.lang.String getBuildingName() {
      java.lang.Object ref = buildingName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildingName_ = s;
        return s;
      }
    }
    /**
     * <code>string building_name = 1;</code>
     * @return The bytes for buildingName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuildingNameBytes() {
      java.lang.Object ref = buildingName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildingName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUILDING_NUMBER_FIELD_NUMBER = 2;
    private int buildingNumber_;
    /**
     * <code>int32 building_number = 2;</code>
     * @return The buildingNumber.
     */
    @java.lang.Override
    public int getBuildingNumber() {
      return buildingNumber_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private exercise2.5StreetPackage.Street address_;
    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.Street address = 3;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return address_ != null;
    }
    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.Street address = 3;</code>
     * @return The address.
     */
    @java.lang.Override
    public exercise2.5StreetPackage.Street getAddress() {
      return address_ == null ? exercise2.5StreetPackage.Street.getDefaultInstance() : address_;
    }
    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.Street address = 3;</code>
     */
    @java.lang.Override
    public exercise2.5StreetPackage.StreetOrBuilder getAddressOrBuilder() {
      return getAddress();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(buildingName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buildingName_);
      }
      if (buildingNumber_ != 0) {
        output.writeInt32(2, buildingNumber_);
      }
      if (address_ != null) {
        output.writeMessage(3, getAddress());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(buildingName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buildingName_);
      }
      if (buildingNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, buildingNumber_);
      }
      if (address_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAddress());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof exercise2.5BuildingPackage.Building)) {
        return super.equals(obj);
      }
      exercise2.5BuildingPackage.Building other = (exercise2.5BuildingPackage.Building) obj;

      if (!getBuildingName()
          .equals(other.getBuildingName())) return false;
      if (getBuildingNumber()
          != other.getBuildingNumber()) return false;
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDING_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingName().hashCode();
      hash = (37 * hash) + BUILDING_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingNumber();
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static exercise2.5BuildingPackage.Building parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exercise2.5BuildingPackage.Building parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exercise2.5BuildingPackage.Building parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exercise2.5BuildingPackage.Building parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exercise2.5BuildingPackage.Building parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exercise2.5BuildingPackage.Building parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exercise2.5BuildingPackage.Building parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static exercise2.5BuildingPackage.Building parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static exercise2.5BuildingPackage.Building parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static exercise2.5BuildingPackage.Building parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static exercise2.5BuildingPackage.Building parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static exercise2.5BuildingPackage.Building parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(exercise2.5BuildingPackage.Building prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code exercise2.Building}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:exercise2.Building)
        exercise2.5BuildingPackage.BuildingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return exercise2.5BuildingPackage.internal_static_exercise2_Building_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return exercise2.5BuildingPackage.internal_static_exercise2_Building_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                exercise2.5BuildingPackage.Building.class, exercise2.5BuildingPackage.Building.Builder.class);
      }

      // Construct using exercise2.5BuildingPackage.Building.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        buildingName_ = "";

        buildingNumber_ = 0;

        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          address_ = null;
          addressBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return exercise2.5BuildingPackage.internal_static_exercise2_Building_descriptor;
      }

      @java.lang.Override
      public exercise2.5BuildingPackage.Building getDefaultInstanceForType() {
        return exercise2.5BuildingPackage.Building.getDefaultInstance();
      }

      @java.lang.Override
      public exercise2.5BuildingPackage.Building build() {
        exercise2.5BuildingPackage.Building result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public exercise2.5BuildingPackage.Building buildPartial() {
        exercise2.5BuildingPackage.Building result = new exercise2.5BuildingPackage.Building(this);
        result.buildingName_ = buildingName_;
        result.buildingNumber_ = buildingNumber_;
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof exercise2.5BuildingPackage.Building) {
          return mergeFrom((exercise2.5BuildingPackage.Building)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(exercise2.5BuildingPackage.Building other) {
        if (other == exercise2.5BuildingPackage.Building.getDefaultInstance()) return this;
        if (!other.getBuildingName().isEmpty()) {
          buildingName_ = other.buildingName_;
          onChanged();
        }
        if (other.getBuildingNumber() != 0) {
          setBuildingNumber(other.getBuildingNumber());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        exercise2.5BuildingPackage.Building parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (exercise2.5BuildingPackage.Building) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object buildingName_ = "";
      /**
       * <code>string building_name = 1;</code>
       * @return The buildingName.
       */
      public java.lang.String getBuildingName() {
        java.lang.Object ref = buildingName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buildingName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string building_name = 1;</code>
       * @return The bytes for buildingName.
       */
      public com.google.protobuf.ByteString
          getBuildingNameBytes() {
        java.lang.Object ref = buildingName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buildingName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string building_name = 1;</code>
       * @param value The buildingName to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buildingName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string building_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingName() {
        
        buildingName_ = getDefaultInstance().getBuildingName();
        onChanged();
        return this;
      }
      /**
       * <code>string building_name = 1;</code>
       * @param value The bytes for buildingName to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buildingName_ = value;
        onChanged();
        return this;
      }

      private int buildingNumber_ ;
      /**
       * <code>int32 building_number = 2;</code>
       * @return The buildingNumber.
       */
      @java.lang.Override
      public int getBuildingNumber() {
        return buildingNumber_;
      }
      /**
       * <code>int32 building_number = 2;</code>
       * @param value The buildingNumber to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingNumber(int value) {
        
        buildingNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 building_number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingNumber() {
        
        buildingNumber_ = 0;
        onChanged();
        return this;
      }

      private exercise2.5StreetPackage.Street address_;
      private com.google.protobuf.SingleFieldBuilderV3<
          exercise2.5StreetPackage.Street, exercise2.5StreetPackage.Street.Builder, exercise2.5StreetPackage.StreetOrBuilder> addressBuilder_;
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.Street address = 3;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return addressBuilder_ != null || address_ != null;
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.Street address = 3;</code>
       * @return The address.
       */
      public exercise2.5StreetPackage.Street getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? exercise2.5StreetPackage.Street.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.Street address = 3;</code>
       */
      public Builder setAddress(exercise2.5StreetPackage.Street value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.Street address = 3;</code>
       */
      public Builder setAddress(
          exercise2.5StreetPackage.Street.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.Street address = 3;</code>
       */
      public Builder mergeAddress(exercise2.5StreetPackage.Street value) {
        if (addressBuilder_ == null) {
          if (address_ != null) {
            address_ =
              exercise2.5StreetPackage.Street.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.Street address = 3;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          address_ = null;
          addressBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.Street address = 3;</code>
       */
      public exercise2.5StreetPackage.Street.Builder getAddressBuilder() {
        
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.Street address = 3;</code>
       */
      public exercise2.5StreetPackage.StreetOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              exercise2.5StreetPackage.Street.getDefaultInstance() : address_;
        }
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.Street address = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          exercise2.5StreetPackage.Street, exercise2.5StreetPackage.Street.Builder, exercise2.5StreetPackage.StreetOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              exercise2.5StreetPackage.Street, exercise2.5StreetPackage.Street.Builder, exercise2.5StreetPackage.StreetOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:exercise2.Building)
    }

    // @@protoc_insertion_point(class_scope:exercise2.Building)
    private static final exercise2.5BuildingPackage.Building DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new exercise2.5BuildingPackage.Building();
    }

    public static exercise2.5BuildingPackage.Building getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Building>
        PARSER = new com.google.protobuf.AbstractParser<Building>() {
      @java.lang.Override
      public Building parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Building(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Building> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Building> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public exercise2.5BuildingPackage.Building getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exercise2_Building_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exercise2_Building_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0305-building-package.proto\022\texercise2\032\0265" +
      "-street-package.proto\"^\n\010Building\022\025\n\rbui" +
      "lding_name\030\001 \001(\t\022\027\n\017building_number\030\002 \001(" +
      "\005\022\"\n\007address\030\003 \001(\0132\021.exercise2.Streetb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          exercise2.5StreetPackage.getDescriptor(),
        });
    internal_static_exercise2_Building_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exercise2_Building_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exercise2_Building_descriptor,
        new java.lang.String[] { "BuildingName", "BuildingNumber", "Address", });
    exercise2.5StreetPackage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
