// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 5-street-package.proto

package exercise2;

public final class 5StreetPackage {
  private 5StreetPackage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StreetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:exercise2.Street)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string addr_line1 = 1;</code>
     * @return The addrLine1.
     */
    java.lang.String getAddrLine1();
    /**
     * <code>string addr_line1 = 1;</code>
     * @return The bytes for addrLine1.
     */
    com.google.protobuf.ByteString
        getAddrLine1Bytes();

    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.City name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.City name = 2;</code>
     * @return The name.
     */
    exercise2.5CityPackage.City getName();
    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.City name = 2;</code>
     */
    exercise2.5CityPackage.CityOrBuilder getNameOrBuilder();
  }
  /**
   * Protobuf type {@code exercise2.Street}
   */
  public static final class Street extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:exercise2.Street)
      StreetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Street.newBuilder() to construct.
    private Street(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Street() {
      addrLine1_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Street();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Street(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              addrLine1_ = s;
              break;
            }
            case 18: {
              exercise2.5CityPackage.City.Builder subBuilder = null;
              if (name_ != null) {
                subBuilder = name_.toBuilder();
              }
              name_ = input.readMessage(exercise2.5CityPackage.City.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(name_);
                name_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return exercise2.5StreetPackage.internal_static_exercise2_Street_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return exercise2.5StreetPackage.internal_static_exercise2_Street_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              exercise2.5StreetPackage.Street.class, exercise2.5StreetPackage.Street.Builder.class);
    }

    public static final int ADDR_LINE1_FIELD_NUMBER = 1;
    private volatile java.lang.Object addrLine1_;
    /**
     * <code>string addr_line1 = 1;</code>
     * @return The addrLine1.
     */
    @java.lang.Override
    public java.lang.String getAddrLine1() {
      java.lang.Object ref = addrLine1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addrLine1_ = s;
        return s;
      }
    }
    /**
     * <code>string addr_line1 = 1;</code>
     * @return The bytes for addrLine1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddrLine1Bytes() {
      java.lang.Object ref = addrLine1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addrLine1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private exercise2.5CityPackage.City name_;
    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.City name = 2;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return name_ != null;
    }
    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.City name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public exercise2.5CityPackage.City getName() {
      return name_ == null ? exercise2.5CityPackage.City.getDefaultInstance() : name_;
    }
    /**
     * <pre>
     * imported
     * </pre>
     *
     * <code>.exercise2.City name = 2;</code>
     */
    @java.lang.Override
    public exercise2.5CityPackage.CityOrBuilder getNameOrBuilder() {
      return getName();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(addrLine1_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addrLine1_);
      }
      if (name_ != null) {
        output.writeMessage(2, getName());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(addrLine1_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addrLine1_);
      }
      if (name_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getName());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof exercise2.5StreetPackage.Street)) {
        return super.equals(obj);
      }
      exercise2.5StreetPackage.Street other = (exercise2.5StreetPackage.Street) obj;

      if (!getAddrLine1()
          .equals(other.getAddrLine1())) return false;
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDR_LINE1_FIELD_NUMBER;
      hash = (53 * hash) + getAddrLine1().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static exercise2.5StreetPackage.Street parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exercise2.5StreetPackage.Street parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exercise2.5StreetPackage.Street parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exercise2.5StreetPackage.Street parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exercise2.5StreetPackage.Street parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exercise2.5StreetPackage.Street parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exercise2.5StreetPackage.Street parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static exercise2.5StreetPackage.Street parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static exercise2.5StreetPackage.Street parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static exercise2.5StreetPackage.Street parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static exercise2.5StreetPackage.Street parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static exercise2.5StreetPackage.Street parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(exercise2.5StreetPackage.Street prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code exercise2.Street}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:exercise2.Street)
        exercise2.5StreetPackage.StreetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return exercise2.5StreetPackage.internal_static_exercise2_Street_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return exercise2.5StreetPackage.internal_static_exercise2_Street_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                exercise2.5StreetPackage.Street.class, exercise2.5StreetPackage.Street.Builder.class);
      }

      // Construct using exercise2.5StreetPackage.Street.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        addrLine1_ = "";

        if (nameBuilder_ == null) {
          name_ = null;
        } else {
          name_ = null;
          nameBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return exercise2.5StreetPackage.internal_static_exercise2_Street_descriptor;
      }

      @java.lang.Override
      public exercise2.5StreetPackage.Street getDefaultInstanceForType() {
        return exercise2.5StreetPackage.Street.getDefaultInstance();
      }

      @java.lang.Override
      public exercise2.5StreetPackage.Street build() {
        exercise2.5StreetPackage.Street result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public exercise2.5StreetPackage.Street buildPartial() {
        exercise2.5StreetPackage.Street result = new exercise2.5StreetPackage.Street(this);
        result.addrLine1_ = addrLine1_;
        if (nameBuilder_ == null) {
          result.name_ = name_;
        } else {
          result.name_ = nameBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof exercise2.5StreetPackage.Street) {
          return mergeFrom((exercise2.5StreetPackage.Street)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(exercise2.5StreetPackage.Street other) {
        if (other == exercise2.5StreetPackage.Street.getDefaultInstance()) return this;
        if (!other.getAddrLine1().isEmpty()) {
          addrLine1_ = other.addrLine1_;
          onChanged();
        }
        if (other.hasName()) {
          mergeName(other.getName());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        exercise2.5StreetPackage.Street parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (exercise2.5StreetPackage.Street) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object addrLine1_ = "";
      /**
       * <code>string addr_line1 = 1;</code>
       * @return The addrLine1.
       */
      public java.lang.String getAddrLine1() {
        java.lang.Object ref = addrLine1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addrLine1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string addr_line1 = 1;</code>
       * @return The bytes for addrLine1.
       */
      public com.google.protobuf.ByteString
          getAddrLine1Bytes() {
        java.lang.Object ref = addrLine1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addrLine1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string addr_line1 = 1;</code>
       * @param value The addrLine1 to set.
       * @return This builder for chaining.
       */
      public Builder setAddrLine1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addrLine1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string addr_line1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddrLine1() {
        
        addrLine1_ = getDefaultInstance().getAddrLine1();
        onChanged();
        return this;
      }
      /**
       * <code>string addr_line1 = 1;</code>
       * @param value The bytes for addrLine1 to set.
       * @return This builder for chaining.
       */
      public Builder setAddrLine1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addrLine1_ = value;
        onChanged();
        return this;
      }

      private exercise2.5CityPackage.City name_;
      private com.google.protobuf.SingleFieldBuilderV3<
          exercise2.5CityPackage.City, exercise2.5CityPackage.City.Builder, exercise2.5CityPackage.CityOrBuilder> nameBuilder_;
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.City name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return nameBuilder_ != null || name_ != null;
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.City name = 2;</code>
       * @return The name.
       */
      public exercise2.5CityPackage.City getName() {
        if (nameBuilder_ == null) {
          return name_ == null ? exercise2.5CityPackage.City.getDefaultInstance() : name_;
        } else {
          return nameBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.City name = 2;</code>
       */
      public Builder setName(exercise2.5CityPackage.City value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          name_ = value;
          onChanged();
        } else {
          nameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.City name = 2;</code>
       */
      public Builder setName(
          exercise2.5CityPackage.City.Builder builderForValue) {
        if (nameBuilder_ == null) {
          name_ = builderForValue.build();
          onChanged();
        } else {
          nameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.City name = 2;</code>
       */
      public Builder mergeName(exercise2.5CityPackage.City value) {
        if (nameBuilder_ == null) {
          if (name_ != null) {
            name_ =
              exercise2.5CityPackage.City.newBuilder(name_).mergeFrom(value).buildPartial();
          } else {
            name_ = value;
          }
          onChanged();
        } else {
          nameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.City name = 2;</code>
       */
      public Builder clearName() {
        if (nameBuilder_ == null) {
          name_ = null;
          onChanged();
        } else {
          name_ = null;
          nameBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.City name = 2;</code>
       */
      public exercise2.5CityPackage.City.Builder getNameBuilder() {
        
        onChanged();
        return getNameFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.City name = 2;</code>
       */
      public exercise2.5CityPackage.CityOrBuilder getNameOrBuilder() {
        if (nameBuilder_ != null) {
          return nameBuilder_.getMessageOrBuilder();
        } else {
          return name_ == null ?
              exercise2.5CityPackage.City.getDefaultInstance() : name_;
        }
      }
      /**
       * <pre>
       * imported
       * </pre>
       *
       * <code>.exercise2.City name = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          exercise2.5CityPackage.City, exercise2.5CityPackage.City.Builder, exercise2.5CityPackage.CityOrBuilder> 
          getNameFieldBuilder() {
        if (nameBuilder_ == null) {
          nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              exercise2.5CityPackage.City, exercise2.5CityPackage.City.Builder, exercise2.5CityPackage.CityOrBuilder>(
                  getName(),
                  getParentForChildren(),
                  isClean());
          name_ = null;
        }
        return nameBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:exercise2.Street)
    }

    // @@protoc_insertion_point(class_scope:exercise2.Street)
    private static final exercise2.5StreetPackage.Street DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new exercise2.5StreetPackage.Street();
    }

    public static exercise2.5StreetPackage.Street getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Street>
        PARSER = new com.google.protobuf.AbstractParser<Street>() {
      @java.lang.Override
      public Street parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Street(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Street> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Street> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public exercise2.5StreetPackage.Street getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exercise2_Street_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exercise2_Street_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0265-street-package.proto\022\texercise2\032\0245-c" +
      "ity-package.proto\";\n\006Street\022\022\n\naddr_line" +
      "1\030\001 \001(\t\022\035\n\004name\030\002 \001(\0132\017.exercise2.Cityb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          exercise2.5CityPackage.getDescriptor(),
        });
    internal_static_exercise2_Street_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exercise2_Street_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exercise2_Street_descriptor,
        new java.lang.String[] { "AddrLine1", "Name", });
    exercise2.5CityPackage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
